#!/bin/bash
#gcc -ggdb3 -D_GNU_SOURCE -DDEBUG -DHTTP_PARSER_STRICT=1 -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c -lev -lpthread -lrt -o NaMo
#gcc -ggdb3 -D_GNU_SOURCE -DSTRINGENT_ERROR_CHECKING -DHTTP_PARSER_STRICT=1 -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c -lev -lpthread -lrt -o NaMo
#g++ -ggdb3 -D_GNU_SOURCE -DHTTP_PARSER_STRICT=0 -O3 -std=c++11 -Wall -Wextra -Wfatal-errors -Werror -pedantic-errors -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c -lev -lpthread -lrt -o NaMo
#g++ -ggdb3 -D_GNU_SOURCE -DHTTP_PARSER_STRICT=0 -std=c++11 -Wall -Wextra -Wfatal-errors -Werror -pedantic-errors -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c -lev -lpthread -lrt -o NaMo
#gcc -ggdb3 -D_GNU_SOURCE -DHTTP_PARSER_STRICT=0 -O2 -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic-errors -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c -lev -lpthread -lrt -o NaMo
#gcc -ggdb3 -DMT_GENERATE_CODE_IN_HEADER=0 -D_GNU_SOURCE -Dlint -DHTTP_PARSER_STRICT=0 -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic-errors -I. -I./include -I/usr/local/include ./util/mtwist.c ./util/Utils.c http_parser.c server.c Config.c hp.c Timer.c ./handlers/hello_world.c ./handlers/default_handler.c ./handlers/getSP.c -lev -lpthread -lrt -lm -o NaMo

gcc -ggdb3 -DMT_GENERATE_CODE_IN_HEADER=0 -D_GNU_SOURCE -Dlint -DHTTP_PARSER_STRICT=1 -DSTRINGENT_ERROR_CHECKING -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic-errors -I. -I./include -I/usr/local/include ./util/mtwist.c ./util/Utils.c http_parser.c server.c Config.c hp.c Timer.c ./handlers/hello_world.c ./handlers/default_handler.c ./handlers/getSP.c -lev -lpthread -lrt -lm -o NaMo
#gcc -ggdb3 -DSTRINGENT_ERROR_CHECKING -DMT_GENERATE_CODE_IN_HEADER=0 -D_GNU_SOURCE -Dlint -DHTTP_PARSER_STRICT=1 -Wall -Wextra -Wfatal-errors -Werror -std=c99 -pedantic-errors -I. -I./include -I/usr/local/include ./util/mtwist.c ./util/Utils.c http_parser.c server.c Config.c hp.c Timer.c ./handlers/hello_world.c ./handlers/default_handler.c ./handlers/getSP.c -lev -lpthread -lrt -o NaMo
#g++ -ggdb3 -D_GNU_SOURCE -Dlint -DHTTP_PARSER_STRICT=0 -Wall -Wextra -Wfatal-errors -Werror -std=c++11 -pedantic-errors -I. -I./include -I/usr/local/include http_parser.c server.c Config.c hp.c Timer.c ./util/Utils.c ./handlers/hello_world.c ./handlers/default_handler.c ./handlers/getSP.c ./util/mtwist.c -lev -lpthread -lrt -o NaMo
