#ifndef __INPC_ERROR__
#define __INPC_ERROR__

#define INPC_ERROR_PAGE_ALLOCATION_FAIL 1
#define INPC_ERROR_SET_FAILED_TOO_BIG_OBJECT 2
#define INPC_ERROR_SET_FAILED_NO_SPACE 3
#define INPC_ERROR_INVALID_SET_COMMAND 4
#define INPC_ERROR_INVALID_GET_PARAMS 5

#define INPC_ERROR_ITEM_EXPIRED 1
#define INPC_ERROR_ITEM_ABSENT 2


#endif
